fixes #20 by conditionally installing xmlrpc at install time.
sensu-plugins/sensu-plugins-supervisor pull request #22
Opened 2017-06-10 17:25 UTC by majormoses

A bit of background:
in ruby version 2.4 they removed xmlrpc from std lib. So we need to conditionally install it depending on what version of ruby is being used on the target system (not the build system).

It seeems tempting (and wrong) to say just put this in the `.gemspec` but this is evaluated at **build** time and we want to check this at **install** time.

To my limited knowledge the only way to do this is to create a ruby extension to check and install at install time. I have commented in the `.gemspec` about this so that its less "silent" when someone is looking through it. I have also included 2 dockerfiles that are meant to be used to test build and install of gem on ruby 2.3 and ruby 2.4 and have appropriate information in README on how to use.

## Pull Request Checklist

The saga of issues related:
#15, #16, #17, #18, #19

This is geared towards solving #20 which should close out any further concerns about this.
#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### Purpose
Conditionally add `xmlrpc` gem as a dep on ruby 2.4 during **install** time vs **build** time.
#### Known Compatibility Issues
None that I am aware of.

2017-06-10 17:30 UTC, majormoses commented
@stuwil can you check this out and give me any feedback?

2017-06-10 17:35 UTC, majormoses commented on lib/sensu-plugins-supervisor/version.rb
> +    MINOR = 1
feel free to tell me to remove this and make it part of the release but it made testing easier and I will release this after it gets merged.

2017-06-11 05:30 UTC, eheydrick requested changes
Oy, that's a yucky problem. Nice fix. Only change I'd like is 2.4 added to travis testing so we validate it installs there.

2017-06-12 06:27 UTC, eheydrick approved these changes

2017-06-12 06:27 UTC, merged

2017-06-12 07:44 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-supervisor/versions/1.1.0